name: "Build Workflow"

on:
  workflow_call:

jobs:
  dockernize:
    runs-on: ubuntu-alpine
    steps:
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t laravel-app .

      - name: Tag Docker image
        run: |
          docker tag laravel-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest

      - name: Push To Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest
