name: "Main Workflow"

on:
    pull_request:
      branches:
      - dev

jobs:
  build:
    name: "Build Laravel App"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: |
          composer install
      
      - name: Setup env
        run: |
          cp .env.ci .env

      - name: Build the app
        run: |
          php artisan key:generate

      - name: MySQL Container
        run: |
          docker run -d -p 3306:3306 mysql:latest &&
          sudo mysql &&
          CREATE USER 'localuser'@'localhost' IDENTIFIED WITH mysql_native_password BY 'localuser'; &&
          CREATE DATABASE test; &&
          GRANT ALL PRIVILEGES ON test.* TO 'localuser'@'localhost' WITH GRANT OPTION; &&
          FLUSH PRIVILEGES;
      
      - name: Migrate The Database
        run: |
          php artisan migrate
      
      - name: Unit Test
        run: 
          php artisan test