name: "Main Workflow"

on:
    pull_request:
      branches:
      - dev

jobs:
  build:
    name: "Build Laravel App"
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          composer install
      - name: Build the app
        run: |
          php artisan key:generate